import type { Level, Spec } from './engine';

const RIVER: Level['water'] = [[4, 0], [4, 1], [4, 2], [4, 3], [4, 4]];

export const LEVELS: Record<string, Level & { solution: Spec }> = {
  'first-steps': {
    id: 'first-steps',
    size: 5,
    start: { cell: [0, 0], dir: 'E' },
    flag: [0, 3],
    gems: [],
    rocks: [],
    trees: [[2, 1]],
    water: RIVER,
    path: [[0, 0], [0, 1], [0, 2], [0, 3]],
    palette: ['move'],
    maxBlocks: 3,
    solution: ['move', 'move', 'move'],
  },
  'turn-corner': {
    id: 'turn-corner',
    size: 5,
    start: { cell: [0, 0], dir: 'E' },
    flag: [2, 2],
    gems: [[0, 2]],
    rocks: [[0, 3]],
    trees: [[1, 0]],
    water: RIVER,
    path: [[0, 0], [0, 1], [0, 2], [1, 2], [2, 2]],
    palette: ['move', 'right', 'left', 'pick'],
    maxBlocks: 6,
    solution: ['move', 'move', 'pick', 'right', 'move', 'move'],
  },
  'gem-row': {
    id: 'gem-row',
    size: 5,
    start: { cell: [0, 0], dir: 'E' },
    flag: [2, 3],
    gems: [[0, 1], [0, 2], [0, 3]],
    rocks: [[2, 1], [0, 4]],
    trees: [[1, 0], [3, 4]],
    water: RIVER,
    path: [[0, 0], [0, 1], [0, 2], [0, 3], [1, 3], [2, 3]],
    palette: ['move', 'right', 'left', 'pick', 'repeat'],
    maxBlocks: 6,
    solution: [{ repeat: 3, body: ['move', 'pick'] }, 'right', 'move', 'move'],
  },
  stairs: {
    id: 'stairs',
    size: 5,
    start: { cell: [0, 0], dir: 'E' },
    flag: [3, 3],
    gems: [[0, 1], [1, 2], [2, 3]],
    rocks: [[0, 2], [1, 3], [2, 4]],
    trees: [[2, 0], [3, 1]],
    water: RIVER,
    path: [[0, 0], [0, 1], [1, 1], [1, 2], [2, 2], [2, 3], [3, 3]],
    palette: ['move', 'right', 'left', 'pick', 'repeat'],
    maxBlocks: 6,
    solution: [{ repeat: 3, body: ['move', 'pick', 'right', 'move', 'left'] }],
  },
  bazaar: {
    id: 'bazaar',
    size: 5,
    start: { cell: [3, 0], dir: 'E' },
    flag: [0, 3],
    gems: [[3, 1], [3, 2], [3, 3], [2, 3], [1, 3]],
    rocks: [[2, 1], [1, 1]],
    trees: [[0, 0], [2, 4]],
    water: [[4, 0], [4, 1], [4, 2], [4, 3], [4, 4]],
    path: [[3, 0], [3, 1], [3, 2], [3, 3], [2, 3], [1, 3], [0, 3]],
    palette: ['move', 'right', 'left', 'pick', 'repeat'],
    maxBlocks: 8,
    solution: [{ repeat: 3, body: ['move', 'pick'] }, 'left', { repeat: 2, body: ['move', 'pick'] }, 'move'],
  },
};

export const getLevel = (id: string) => LEVELS[id];
