import { bug, lesson, order, predict, quiz, read, tap } from '../dsl';
import type { Lesson } from '../types';

const K = 'C';

export const C_LESSONS: Lesson[] = [
  lesson('c-hello', 'Hello, C', 'c', ['Every C program starts at main()', 'printf prints text', '\\n starts a new line'], [
    read({
      kicker: `READ · ${K}`,
      title: 'The language under everything',
      body: 'C is fast and close to the hardware. Operating systems, games and even Python itself are written in C. Every program starts running at main(), and printf prints text.',
      lang: 'c',
      code: ['#include <stdio.h>', '', 'int main() {', '    printf("Namaste, C!\\n");', '    return 0;', '}'],
      tip: '#include <stdio.h> brings in printf. return 0 tells the system the program finished fine.',
    }),
    tap({
      kicker: `PRACTICE · ${K}`,
      title: 'Find the print function',
      instructions: 'Tap the function that prints text to the screen.',
      lang: 'c',
      lines: ['#include <stdio.h>', 'int main() {', '    printf("Hi\\n");', '    return 0;', '}'],
      target: { line: 2, token: 'printf' },
      explain: 'printf ("print formatted") writes text to the screen.',
    }),
    order({
      kicker: `PRACTICE · ${K}`,
      title: 'Build your first program',
      instructions: 'Put the lines in order so the program compiles and prints a greeting.',
      lang: 'c',
      lines: ['#include <stdio.h>', 'int main() {', '    printf("Chalo, code karein!\\n");', '    return 0;', '}'],
      output: ['Chalo, code karein!'],
      explain: 'Include first, then main with its body between { and }.',
    }),
    predict({
      kicker: `PRACTICE · ${K}`,
      title: 'What prints?',
      lang: 'c',
      lines: ['#include <stdio.h>', 'int main() {', '    printf("Code");', '    printf("Yatra\\n");', '    return 0;', '}'],
      answer: 'CodeYatra',
      explain: 'Without \\n, the second printf continues on the same line.',
    }),
  ]),

  lesson('c-vars', 'Variables and types', 'c', ['C needs a type for every variable', '%d, %f, %c print int, float, char', 'Integer division drops the decimal'], [
    read({
      kicker: `READ · ${K}`,
      title: 'Every box has a type',
      body: 'In C you say what kind of value a variable holds: int for whole numbers, float for decimals, char for one letter. printf uses a placeholder for each type.',
      lang: 'c',
      code: ['int seats = 42;', 'float fare = 199.5;', "char coach = 'B';", 'printf("%d seats, Rs %.1f, coach %c\\n", seats, fare, coach);'],
      tip: '%.1f means "one digit after the decimal point".',
    }),
    quiz({
      prompt: 'Which placeholder prints an int?',
      options: ['%d', '%f', '%c', '%s'],
      mono: true,
      right: '%d is for decimal integers.',
      wrong: '%f is for floats, %c for a char, %s for a string. Integers use %d.',
    }),
    predict({
      kicker: `PRACTICE · ${K}`,
      title: 'Integer division',
      lang: 'c',
      lines: ['#include <stdio.h>', 'int main() {', '    int a = 7, b = 2;', '    printf("%d %d\\n", a / b, a % b);', '    return 0;', '}'],
      answer: '3 1',
      explain: '7 / 2 between ints is 3 (the decimal is dropped). 7 % 2 is the remainder, 1.',
    }),
    bug({
      kicker: `PRACTICE · ${K}`,
      title: 'Wrong placeholder',
      instructions: 'This should print the fare 150.50. Which line is wrong?',
      lang: 'c',
      lines: ['#include <stdio.h>', 'int main() {', '    float fare = 150.5;', '    printf("%d\\n", fare);', '    return 0;', '}'],
      bug: 3,
      fix: '    printf("%.2f\\n", fare);',
      explain: 'A float needs %f (here %.2f for two decimals). %d expects an int and prints garbage.',
    }),
  ]),

  lesson('c-if', 'Decisions with if', 'c', ['if runs code only when a condition is true', '== compares, = assigns', 'else if checks the next condition'], [
    read({
      kicker: `READ · ${K}`,
      title: 'Let the program decide',
      body: 'if (condition) runs its block only when the condition is true. Add else for the other case. Compare with ==, and remember = means "store a value", not "is equal".',
      lang: 'c',
      code: ['int marks = 72;', 'if (marks >= 90) {', '    printf("A\\n");', '} else if (marks >= 60) {', '    printf("B\\n");', '} else {', '    printf("C\\n");', '}'],
      tip: 'In C, any non-zero number counts as true.',
    }),
    predict({
      kicker: `PRACTICE · ${K}`,
      title: 'Which grade?',
      lang: 'c',
      lines: [
        '#include <stdio.h>',
        'int main() {',
        '    int marks = 72;',
        '    if (marks >= 90) printf("A\\n");',
        '    else if (marks >= 60) printf("B\\n");',
        '    else printf("C\\n");',
        '    return 0;',
        '}',
      ],
      answer: 'B',
      explain: '72 is not ≥ 90, but it is ≥ 60, so the else if branch runs.',
    }),
    bug({
      kicker: `PRACTICE · ${K}`,
      title: 'The sneaky equals',
      instructions: 'Seats are 0, so this should print "Full". It prints "Seats left". Find the bug.',
      lang: 'c',
      lines: [
        '#include <stdio.h>',
        'int main() {',
        '    int seats = 0;',
        '    if (seats = 0) printf("Full\\n");',
        '    else printf("Seats left\\n");',
        '    return 0;',
        '}',
      ],
      bug: 3,
      fix: '    if (seats == 0) printf("Full\\n");',
      explain: 'seats = 0 stores 0 and the condition becomes 0 (false). Use == to compare.',
    }),
  ]),

  lesson('c-loops', 'Loops', 'c', ['for repeats a known number of times', 'while repeats until a condition is false', 'i++ adds one to i'], [
    read({
      kicker: `READ · ${K}`,
      title: 'Repeat without copy-paste',
      body: 'A for loop has three parts: start, condition, step. It runs the body while the condition is true. A while loop just checks a condition each time.',
      lang: 'c',
      code: ['for (int i = 1; i <= 3; i++) {', '    printf("%d ", i);', '}', '// prints: 1 2 3'],
      tip: 'Forgetting i++ in a while loop is the classic infinite loop.',
    }),
    order({
      kicker: `PRACTICE · ${K}`,
      title: 'Countdown',
      instructions: 'Arrange the program so it counts down 3, 2, 1, then prints Go!',
      lang: 'c',
      lines: ['#include <stdio.h>', 'int main() {', '    for (int i = 3; i >= 1; i--) {', '        printf("%d\\n", i);', '    }', '    printf("Go!\\n");', '    return 0;', '}'],
      output: ['3', '2', '1', 'Go!'],
      explain: 'The loop counts down with i--, and "Go!" prints once, after the loop.',
    }),
    predict({
      kicker: `PRACTICE · ${K}`,
      title: 'Sum it up',
      lang: 'c',
      lines: ['#include <stdio.h>', 'int main() {', '    int sum = 0;', '    for (int i = 1; i <= 4; i++) sum += i;', '    printf("%d\\n", sum);', '    return 0;', '}'],
      answer: '10',
      explain: '1 + 2 + 3 + 4 = 10.',
    }),
  ]),

  lesson('c-func', 'Functions', 'c', ['A function has a return type, name and parameters', 'return sends a value back', 'Declare before you call'], [
    read({
      kicker: `READ · ${K}`,
      title: 'Name a piece of work',
      body: 'A function packs steps under a name. In C you write the return type first, then the name and typed parameters.',
      lang: 'c',
      code: ['int square(int n) {', '    return n * n;', '}', '', 'printf("%d\\n", square(5)); // 25'],
      tip: 'void means the function returns nothing.',
    }),
    tap({
      kicker: `PRACTICE · ${K}`,
      title: 'Spot the return type',
      instructions: 'Tap the word that says what type this function gives back.',
      lang: 'c',
      lines: ['float average(int a, int b) {', '    return (a + b) / 2.0;', '}'],
      target: { line: 0, token: 'float' },
      explain: 'The type before the name, float, is what the function returns.',
    }),
    predict({
      kicker: `PRACTICE · ${K}`,
      title: 'Call it twice',
      lang: 'c',
      lines: ['#include <stdio.h>', 'int fare(int km) {', '    return 20 + km * 2;', '}', 'int main() {', '    printf("%d %d\\n", fare(5), fare(10));', '    return 0;', '}'],
      answer: '30 40',
      explain: '20 + 5×2 = 30 and 20 + 10×2 = 40.',
    }),
  ]),

  lesson('c-arrays', 'Arrays', 'c', ['An array holds many values of one type', 'Indexes start at 0', 'The last index is size - 1'], [
    read({
      kicker: `READ · ${K}`,
      title: 'Many values, one name',
      body: 'int marks[5] makes room for five ints. marks[0] is the first and marks[4] the last. Reading past the end is a bug C will not stop you from making.',
      lang: 'c',
      code: ['int marks[5] = {80, 65, 90, 72, 58};', 'printf("%d\\n", marks[2]); // 90'],
      tip: 'Loop with i < size, not i <= size.',
    }),
    predict({
      kicker: `PRACTICE · ${K}`,
      title: 'Find the topper',
      lang: 'c',
      lines: [
        '#include <stdio.h>',
        'int main() {',
        '    int marks[5] = {80, 65, 90, 72, 58};',
        '    int best = marks[0];',
        '    for (int i = 1; i < 5; i++)',
        '        if (marks[i] > best) best = marks[i];',
        '    printf("%d\\n", best);',
        '    return 0;',
        '}',
      ],
      answer: '90',
      explain: 'best starts at 80 and updates to 90 when it finds a bigger value.',
    }),
    bug({
      kicker: `PRACTICE · ${K}`,
      title: 'One too many',
      instructions: 'This sums the array, but it reads past the end. Which line is wrong?',
      lang: 'c',
      lines: [
        '#include <stdio.h>',
        'int main() {',
        '    int a[3] = {4, 5, 6};',
        '    int sum = 0;',
        '    for (int i = 0; i <= 3; i++) sum += a[i];',
        '    printf("%d\\n", sum);',
        '    return 0;',
        '}',
      ],
      bug: 4,
      fix: '    for (int i = 0; i < 3; i++) sum += a[i];',
      explain: 'a has indexes 0, 1, 2. i <= 3 also reads a[3], which is outside the array.',
    }),
  ]),

  lesson('c-strings', 'Strings', 'c', ['A string is a char array ending in \\0', 'strlen counts characters', '%s prints a string'], [
    read({
      kicker: `READ · ${K}`,
      title: 'Text is an array of chars',
      body: 'C has no string type. "Delhi" is stored as six chars: D, e, l, h, i and a hidden \\0 that marks the end. string.h has helpers like strlen.',
      lang: 'c',
      code: ['#include <string.h>', 'char city[] = "Delhi";', 'printf("%s has %d letters\\n", city, (int) strlen(city));'],
      tip: 'Make char arrays one bigger than the text, for the \\0.',
    }),
    quiz({
      prompt: 'How many bytes does char s[] = "Goa"; use?',
      options: ['4', '3', '2', '8'],
      right: 'Three letters plus the \\0 terminator.',
      wrong: 'Count the hidden \\0 at the end: G, o, a, \\0 → 4.',
    }),
    predict({
      kicker: `PRACTICE · ${K}`,
      title: 'Length and first letter',
      lang: 'c',
      lines: ['#include <stdio.h>', '#include <string.h>', 'int main() {', '    char city[] = "Pune";', '    printf("%c %d\\n", city[0], (int) strlen(city));', '    return 0;', '}'],
      answer: 'P 4',
      explain: 'city[0] is P, and strlen does not count the \\0.',
    }),
  ]),

  lesson('c-pointers', 'Pointers', 'c', ['A pointer stores an address', '&x gives the address of x', '*p reads or changes what p points at'], [
    read({
      kicker: `READ · ${K}`,
      title: 'Addresses, not values',
      body: 'Every variable lives at an address in memory. A pointer holds that address. &x means "address of x"; *p means "the value at the address in p".',
      lang: 'c',
      code: ['int x = 10;', 'int *p = &x;', '*p = 25;', 'printf("%d\\n", x); // 25'],
      tip: 'Pointers let a function change the caller\'s variables.',
    }),
    predict({
      kicker: `PRACTICE · ${K}`,
      title: 'Swap with pointers',
      lang: 'c',
      lines: [
        '#include <stdio.h>',
        'void swap(int *a, int *b) {',
        '    int t = *a;',
        '    *a = *b;',
        '    *b = t;',
        '}',
        'int main() {',
        '    int x = 1, y = 2;',
        '    swap(&x, &y);',
        '    printf("%d %d\\n", x, y);',
        '    return 0;',
        '}',
      ],
      answer: '2 1',
      explain: 'swap receives addresses, so it changes the real x and y.',
    }),
    quiz({
      prompt: 'p = &x. What does *p give?',
      options: ['The value of x', 'The address of x', 'The address of p', 'Always 0'],
      right: '*p follows the address to the value stored there.',
      wrong: 'p holds the address; *p reads the value at that address, which is x.',
    }),
  ]),

  lesson('c-struct', 'Structs', 'c', ['struct groups related fields', 'Access fields with a dot', 'Arrays of structs model tables'], [
    read({
      kicker: `READ · ${K}`,
      title: 'Your own data type',
      body: 'A struct bundles fields into one type, like a row in a table. Read a field with a dot: t.fare.',
      lang: 'c',
      code: ['struct Train {', '    int number;', '    int fare;', '};', 'struct Train t = {12951, 2900};', 'printf("%d\\n", t.fare);'],
      tip: 'Use typedef to skip writing "struct" every time.',
    }),
    predict({
      kicker: `PRACTICE · ${K}`,
      title: 'Cheapest ticket',
      lang: 'c',
      lines: [
        '#include <stdio.h>',
        'struct Train { int number; int fare; };',
        'int main() {',
        '    struct Train t[3] = {{12951, 2900}, {12002, 1200}, {22436, 1750}};',
        '    int best = 0;',
        '    for (int i = 1; i < 3; i++)',
        '        if (t[i].fare < t[best].fare) best = i;',
        '    printf("%d\\n", t[best].number);',
        '    return 0;',
        '}',
      ],
      answer: '12002',
      explain: '1200 is the lowest fare, and that train is 12002.',
    }),
    order({
      kicker: `PRACTICE · ${K}`,
      title: 'Define and use a struct',
      instructions: 'Put the lines in order to define a Point and print its x.',
      lang: 'c',
      lines: ['#include <stdio.h>', 'struct Point { int x; int y; };', 'int main() {', '    struct Point p = {3, 4};', '    printf("%d\\n", p.x);', '    return 0;', '}'],
      output: ['3'],
      explain: 'Define the struct before main uses it.',
    }),
  ]),

  lesson('c-memory', 'Dynamic memory', 'c', ['malloc asks for memory at run time', 'free gives it back', 'Always check malloc did not return NULL'], [
    read({
      kicker: `READ · ${K}`,
      title: 'Memory on demand',
      body: 'Arrays have a fixed size. malloc reserves memory while the program runs, which is how you handle input of any size. Every malloc needs a matching free.',
      lang: 'c',
      code: ['#include <stdlib.h>', 'int *a = malloc(n * sizeof(int));', 'if (a == NULL) return 1;', '/* use a[0] .. a[n-1] */', 'free(a);'],
      tip: 'Memory you never free is a "memory leak".',
    }),
    predict({
      kicker: `PRACTICE · ${K}`,
      title: 'Fill a dynamic array',
      lang: 'c',
      lines: [
        '#include <stdio.h>',
        '#include <stdlib.h>',
        'int main() {',
        '    int n = 4;',
        '    int *a = malloc(n * sizeof(int));',
        '    if (a == NULL) return 1;',
        '    for (int i = 0; i < n; i++) a[i] = i * i;',
        '    printf("%d\\n", a[3]);',
        '    free(a);',
        '    return 0;',
        '}',
      ],
      answer: '9',
      explain: 'a[3] = 3 × 3 = 9.',
    }),
    quiz({
      prompt: 'What should follow every successful malloc?',
      options: ['A matching free', 'A printf', 'Another malloc', 'return 0'],
      right: 'free returns the memory so the program does not leak.',
      wrong: 'Memory from malloc stays reserved until you call free.',
    }),
  ]),
];
