import { bug, lesson, order, predict, quiz, read, tap } from '../dsl';
import type { Lesson } from '../types';

const K = 'JAVA';

export const JAVA_LESSONS: Lesson[] = [
  lesson('jv-hello', 'Hello, Java', 'java', ['Code lives inside a class', 'Programs start at main', 'System.out.println prints a line'], [
    read({
      kicker: `READ · ${K}`,
      title: 'Write once, run anywhere',
      body: 'Java runs on billions of devices, from Android phones to bank servers. Every line of code lives inside a class, and the program starts in the main method.',
      lang: 'java',
      code: ['public class Main {', '    public static void main(String[] args) {', '        System.out.println("Namaste, Java!");', '    }', '}'],
      tip: 'The file name must match the public class: Main.java.',
    }),
    tap({
      kicker: `PRACTICE · ${K}`,
      title: 'Where does it start?',
      instructions: 'Tap the name of the method where every Java program begins.',
      lang: 'java',
      lines: ['public class Main {', '    public static void main(String[] args) {', '        System.out.println("Hi");', '    }', '}'],
      target: { line: 1, token: 'main' },
      explain: 'The JVM looks for public static void main(String[] args) and starts there.',
    }),
    order({
      kicker: `PRACTICE · ${K}`,
      title: 'Assemble the program',
      instructions: 'Put the lines in order to print a greeting.',
      lang: 'java',
      lines: ['public class Main {', '    public static void main(String[] args) {', '        System.out.println("Chalo!");', '    }', '}'],
      explain: 'Class, then main, then the statement, then close both braces.',
    }),
    predict({
      kicker: `PRACTICE · ${K}`,
      title: 'print vs println',
      lang: 'java',
      lines: ['System.out.print("Code");', 'System.out.println("Yatra");', 'System.out.println("!");'],
      answer: 'CodeYatra\n!',
      explain: 'print stays on the same line; println ends the line.',
    }),
  ]),

  lesson('jv-vars', 'Variables and types', 'java', ['Every variable has a type', 'int / int drops the decimal', 'Strings join with +'], [
    read({
      kicker: `READ · ${K}`,
      title: 'Typed boxes',
      body: 'Java checks types before running: int for whole numbers, double for decimals, boolean for true/false, String for text. + joins Strings together.',
      lang: 'java',
      code: ['int seats = 42;', 'double fare = 199.5;', 'boolean ac = true;', 'String name = "Asha";', 'System.out.println(name + " has " + seats + " seats");'],
      tip: 'String starts with a capital S: it is a class, not a primitive.',
    }),
    predict({
      kicker: `PRACTICE · ${K}`,
      title: 'Divide carefully',
      lang: 'java',
      lines: ['int a = 7;', 'int b = 2;', 'System.out.println(a / b);', 'System.out.println(a / 2.0);'],
      answer: '3\n3.5',
      explain: 'Two ints give an int (3). With a double, the result keeps its decimals (3.5).',
    }),
    quiz({
      prompt: 'What is "1" + 2 + 3 in Java?',
      options: ['"123"', '6', '"15"', 'An error'],
      mono: true,
      right: 'Once a String appears, + joins left to right: "1"+2 = "12", then "123".',
      wrong: 'Evaluation goes left to right and "1" is a String, so everything is joined: "123".',
    }),
  ]),

  lesson('jv-if', 'Conditions', 'java', ['if / else if / else choose a path', '&& means and, || means or', 'Compare Strings with equals'], [
    read({
      kicker: `READ · ${K}`,
      title: 'Choose a path',
      body: 'if runs a block when its condition is true. Combine conditions with && (and) and || (or).',
      lang: 'java',
      code: ['int age = 17;', 'boolean hasTicket = true;', 'if (age >= 18 && hasTicket) {', '    System.out.println("Board");', '} else {', '    System.out.println("Wait");', '}'],
      tip: 'Use .equals() to compare Strings, never ==.',
    }),
    predict({
      kicker: `PRACTICE · ${K}`,
      title: 'Ticket price',
      lang: 'java',
      lines: ['int age = 65;', 'int fare = 500;', 'if (age < 5) fare = 0;', 'else if (age >= 60) fare = fare / 2;', 'System.out.println(fare);'],
      answer: '250',
      explain: '65 is not under 5 but is 60 or more, so the senior half fare applies.',
    }),
    bug({
      kicker: `PRACTICE · ${K}`,
      title: 'Comparing text',
      instructions: 'This sometimes says the cities differ even when they are the same. Which line is wrong?',
      lang: 'java',
      lines: ['String from = scanner.next();', 'String home = "Delhi";', 'if (from == home) {', '    System.out.println("Welcome home");', '}'],
      bug: 2,
      fix: 'if (from.equals(home)) {',
      explain: '== checks if two variables point to the same object. equals compares the text.',
    }),
  ]),

  lesson('jv-loops', 'Loops', 'java', ['for counts through a range', 'while repeats until false', 'break leaves a loop early'], [
    read({
      kicker: `READ · ${K}`,
      title: 'Repeat with for and while',
      body: 'for (start; condition; step) is perfect for counting. while keeps going as long as a condition holds. break jumps out of the loop.',
      lang: 'java',
      code: ['for (int i = 1; i <= 3; i++) {', '    System.out.println("Station " + i);', '}'],
      tip: 'The enhanced for, for (int m : marks), loops over every element of an array.',
    }),
    predict({
      kicker: `PRACTICE · ${K}`,
      title: 'Even numbers',
      lang: 'java',
      lines: ['for (int i = 2; i <= 8; i += 2) {', '    System.out.print(i + " ");', '}'],
      answer: '2 4 6 8',
      explain: 'i starts at 2 and grows by 2 until it passes 8.',
    }),
    order({
      kicker: `PRACTICE · ${K}`,
      title: 'Stop at the first full train',
      instructions: 'Arrange the loop so it prints the index of the first train with 0 seats, then stops.',
      lang: 'java',
      lines: ['int[] seats = {5, 3, 0, 8};', 'for (int i = 0; i < seats.length; i++) {', '    if (seats[i] == 0) {', '        System.out.println(i);', '        break;', '    }', '}'],
      explain: 'break stops the loop as soon as the full train is found (index 2).',
    }),
  ]),

  lesson('jv-methods', 'Methods', 'java', ['A method has a return type and parameters', 'static methods belong to the class', 'return ends the method with a value'], [
    read({
      kicker: `READ · ${K}`,
      title: 'Reusable steps',
      body: 'A method is Java\'s word for a function. Write the return type, the name, then typed parameters. void means nothing is returned.',
      lang: 'java',
      code: ['static int fare(int km) {', '    return 20 + km * 2;', '}', '', 'System.out.println(fare(10)); // 40'],
      tip: 'Two methods can share a name if their parameters differ. That is "overloading".',
    }),
    tap({
      kicker: `PRACTICE · ${K}`,
      title: 'Return type',
      instructions: 'Tap the word that says this method gives nothing back.',
      lang: 'java',
      lines: ['static void greet(String name) {', '    System.out.println("Hi " + name);', '}'],
      target: { line: 0, token: 'void' },
      explain: 'void means the method returns no value.',
    }),
    predict({
      kicker: `PRACTICE · ${K}`,
      title: 'Max of two',
      lang: 'java',
      lines: ['static int max(int a, int b) {', '    return a > b ? a : b;', '}', '', 'System.out.println(max(4, 9) + max(7, 3));'],
      answer: '16',
      explain: 'max(4, 9) is 9 and max(7, 3) is 7; 9 + 7 = 16.',
    }),
  ]),

  lesson('jv-arrays', 'Arrays', 'java', ['Arrays have a fixed length', 'arr.length gives the size', 'Indexes run from 0 to length - 1'], [
    read({
      kicker: `READ · ${K}`,
      title: 'A row of values',
      body: 'int[] marks = {80, 65, 90} creates an array of three ints. marks.length is 3. Reading marks[3] throws ArrayIndexOutOfBoundsException.',
      lang: 'java',
      code: ['int[] marks = {80, 65, 90};', 'int total = 0;', 'for (int m : marks) total += m;', 'System.out.println(total); // 235'],
      tip: 'length on arrays has no brackets; length() on Strings does.',
    }),
    predict({
      kicker: `PRACTICE · ${K}`,
      title: 'Average marks',
      lang: 'java',
      lines: ['int[] marks = {70, 80, 90};', 'int sum = 0;', 'for (int m : marks) sum += m;', 'System.out.println(sum / marks.length);'],
      answer: '80',
      explain: '240 / 3 = 80.',
    }),
    bug({
      kicker: `PRACTICE · ${K}`,
      title: 'Out of bounds',
      instructions: 'This crashes with ArrayIndexOutOfBoundsException. Find the bug.',
      lang: 'java',
      lines: ['int[] a = {1, 2, 3};', 'for (int i = 0; i <= a.length; i++) {', '    System.out.println(a[i]);', '}'],
      bug: 1,
      fix: 'for (int i = 0; i < a.length; i++) {',
      explain: 'The last index is a.length - 1, so the loop must use <.',
    }),
  ]),

  lesson('jv-strings', 'Strings', 'java', ['length() counts characters', 'charAt(i) reads one character', 'Strings cannot be changed in place'], [
    read({
      kicker: `READ · ${K}`,
      title: 'Working with text',
      body: 'Strings come with handy methods: length(), charAt(i), toUpperCase(), contains(), substring(a, b). Strings are immutable: methods return a new String.',
      lang: 'java',
      code: ['String city = "Mumbai";', 'System.out.println(city.length());      // 6', 'System.out.println(city.charAt(0));     // M', 'System.out.println(city.toUpperCase()); // MUMBAI'],
      tip: 'Use StringBuilder when you build a long string in a loop.',
    }),
    predict({
      kicker: `PRACTICE · ${K}`,
      title: 'Substring',
      lang: 'java',
      lines: ['String code = "NDLS-BCT";', 'System.out.println(code.substring(0, 4));', 'System.out.println(code.indexOf("-"));'],
      answer: 'NDLS\n4',
      explain: 'substring(0, 4) takes characters 0 to 3; the dash is at index 4.',
    }),
    quiz({
      prompt: 's = "hi"; s.toUpperCase(); What is s now?',
      options: ['"hi"', '"HI"', '"Hi"', 'null'],
      mono: true,
      right: 'Strings are immutable. toUpperCase returns a new String that was thrown away.',
      wrong: 'The method returns a new String; s itself never changes. Write s = s.toUpperCase().',
    }),
  ]),

  lesson('jv-classes', 'Classes and objects', 'java', ['A class is a blueprint', 'new creates an object', 'A constructor sets up fields'], [
    read({
      kicker: `READ · ${K}`,
      title: 'Blueprints and objects',
      body: 'A class describes what an object knows (fields) and does (methods). new Train(...) builds an object from the blueprint, running its constructor.',
      lang: 'java',
      code: [
        'class Train {',
        '    String name;',
        '    int seats;',
        '    Train(String name, int seats) {',
        '        this.name = name;',
        '        this.seats = seats;',
        '    }',
        '    boolean isFull() { return seats == 0; }',
        '}',
      ],
      tip: 'this.name means "the field", name alone means "the parameter".',
    }),
    predict({
      kicker: `PRACTICE · ${K}`,
      title: 'Book a seat',
      lang: 'java',
      lines: ['Train t = new Train("Shatabdi", 1);', 't.seats--;', 'System.out.println(t.name + " " + t.isFull());'],
      answer: 'Shatabdi true',
      explain: 'seats drops from 1 to 0, so isFull() returns true.',
    }),
    quiz({
      prompt: 'Which keyword creates a new object?',
      options: ['new', 'class', 'this', 'static'],
      mono: true,
      right: 'new allocates the object and runs the constructor.',
      wrong: 'class defines the blueprint; new builds an object from it.',
    }),
  ]),

  lesson('jv-oop', 'Inheritance', 'java', ['extends reuses a parent class', '@Override replaces a method', 'A parent variable can hold a child object'], [
    read({
      kicker: `READ · ${K}`,
      title: 'Build on what exists',
      body: 'class Express extends Train gets all of Train\'s fields and methods, and can override some. Calling a method on a Train variable runs the child\'s version: that is polymorphism.',
      lang: 'java',
      code: [
        'class Train {',
        '    int fare() { return 100; }',
        '}',
        'class Express extends Train {',
        '    @Override',
        '    int fare() { return 250; }',
        '}',
      ],
      tip: 'Java allows only one parent class, but many interfaces.',
    }),
    predict({
      kicker: `PRACTICE · ${K}`,
      title: 'Which fare?',
      lang: 'java',
      lines: ['Train a = new Train();', 'Train b = new Express();', 'System.out.println(a.fare() + b.fare());'],
      answer: '350',
      explain: 'b is declared as Train but is an Express, so its fare() is 250. 100 + 250 = 350.',
    }),
    tap({
      kicker: `PRACTICE · ${K}`,
      title: 'Inherit',
      instructions: 'Tap the keyword that makes Sleeper a kind of Train.',
      lang: 'java',
      lines: ['class Sleeper extends Train {', '    int berths = 72;', '}'],
      target: { line: 0, token: 'extends' },
      explain: 'extends sets the parent class.',
    }),
  ]),

  lesson('jv-collections', 'ArrayList and HashMap', 'java', ['ArrayList grows as you add', 'HashMap maps keys to values', 'Use wrapper types like Integer'], [
    read({
      kicker: `READ · ${K}`,
      title: 'Collections that grow',
      body: 'ArrayList is a resizable list; HashMap stores key → value pairs. Both live in java.util and hold objects, so use Integer instead of int.',
      lang: 'java',
      code: [
        'List<String> stops = new ArrayList<>();',
        'stops.add("Delhi");',
        'stops.add("Agra");',
        'Map<String, Integer> fare = new HashMap<>();',
        'fare.put("Agra", 450);',
        'System.out.println(stops.size() + " " + fare.get("Agra"));',
      ],
      tip: 'getOrDefault(key, 0) avoids a null when the key is missing.',
    }),
    predict({
      kicker: `PRACTICE · ${K}`,
      title: 'Count passengers',
      lang: 'java',
      lines: [
        'Map<String, Integer> count = new HashMap<>();',
        'String[] names = {"Asha", "Ravi", "Asha"};',
        'for (String n : names) count.put(n, count.getOrDefault(n, 0) + 1);',
        'System.out.println(count.get("Asha"));',
      ],
      answer: '2',
      explain: 'Asha appears twice, so her count reaches 2.',
    }),
    quiz({
      prompt: 'Which can hold a growing list of names?',
      options: ['ArrayList<String>', 'String[3]', 'int', 'HashMap<Integer>'],
      mono: true,
      right: 'ArrayList resizes as you add items.',
      wrong: 'Arrays have a fixed size. ArrayList grows as you add.',
    }),
  ]),
];
