// Extra practice for each Python module: new exercises, opened from the module's "Practice" button.
import { bug, order, predict, quiz, tap } from '../dsl';
import type { Step } from '../types';

const K = 'PRACTICE · PYTHON';

export const PYTHON_DRILLS: Record<string, Step[]> = {
  // Variables and f-strings
  'p-var-1': [
    predict({
      kicker: K,
      title: 'What does this print?',
      lang: 'python',
      lines: ['seats = 72', 'booked = 65', 'print(f"{seats - booked} seats left")'],
      answer: '7 seats left',
      explain: 'Inside an f-string, the part in { } is worked out first: 72 - 65 is 7.',
    }),
    bug({
      kicker: K,
      title: 'Find the bug',
      instructions: 'This should print "Ticket for Asha". Tap the line with the mistake.',
      lang: 'python',
      lines: ['name = "Asha"', 'print("Ticket for {name}")'],
      bug: 1,
      fix: 'print(f"Ticket for {name}")',
      explain: 'Without the f before the quotes, Python prints {name} as plain text.',
    }),
    predict({
      kicker: K,
      title: 'Values change',
      lang: 'python',
      lines: ['score = 10', 'score = score + 5', 'score = score * 2', 'print(score)'],
      answer: '30',
      explain: 'Each line uses the latest value: 10, then 15, then 30.',
    }),
    quiz({
      prompt: 'Which name is NOT allowed for a Python variable?',
      options: ['2nd_place', 'second_place', 'place2', '_place'],
      right: 'Right. A variable name can’t start with a digit.',
      wrong: 'Names may contain digits and underscores, but they can’t start with a digit.',
      mono: true,
    }),
  ],

  // String methods
  'p-str-1': [
    predict({
      kicker: K,
      title: 'Upper and lower',
      lang: 'python',
      lines: ['city = "Pune"', 'print(city.upper(), city.lower())'],
      answer: 'PUNE pune',
      explain: 'upper() and lower() return new strings; print puts a space between them.',
    }),
    predict({
      kicker: K,
      title: 'Slicing',
      lang: 'python',
      lines: ['code = "CHENNAI"', 'print(code[:3])'],
      answer: 'CHE',
      explain: '[:3] takes characters 0, 1 and 2, stopping before index 3.',
    }),
    bug({
      kicker: K,
      title: 'Find the bug',
      instructions: 'This should print "MUMBAI". Tap the buggy line.',
      lang: 'python',
      lines: ['city = "mumbai"', 'city.upper()', 'print(city)'],
      bug: 1,
      fix: 'city = city.upper()',
      explain: 'Strings never change in place. upper() returns a new string, so store it back in city.',
    }),
    predict({
      kicker: K,
      title: 'Count and replace',
      lang: 'python',
      lines: ['word = "banana"', 'print(word.count("a"), word.replace("a", "o"))'],
      answer: '3 bonono',
      explain: 'count finds 3 a’s; replace swaps every "a" for "o".',
    }),
  ],

  // Counting with range()
  'p-loop-1': [
    predict({
      kicker: K,
      title: 'Where does range stop?',
      lang: 'python',
      lines: ['for i in range(2, 6):', '    print(i, end=" ")'],
      answer: '2 3 4 5',
      explain: 'range(2, 6) starts at 2 and stops before 6.',
    }),
    predict({
      kicker: K,
      title: 'Counting in steps',
      lang: 'python',
      lines: ['for i in range(10, 0, -3):', '    print(i)'],
      answer: '10\n7\n4\n1',
      accept: ['10 7 4 1'],
      explain: 'A step of -3 counts down: 10, 7, 4, 1. The next would be -2, which is past the stop.',
    }),
    order({
      kicker: K,
      title: 'Add up 1 to 5',
      instructions: 'Arrange the lines so the program prints 15.',
      lang: 'python',
      lines: ['total = 0', 'for n in range(1, 6):', '    total = total + n', 'print(total)'],
      output: ['15'],
      explain: 'Start total at 0, add each n inside the loop, and print once the loop is done.',
    }),
    bug({
      kicker: K,
      title: 'Find the bug',
      instructions: 'This should print the 5 times table from 5 × 1 to 5 × 10. Tap the buggy line.',
      lang: 'python',
      lines: ['for i in range(1, 10):', '    print(5, "x", i, "=", 5 * i)'],
      bug: 0,
      fix: 'for i in range(1, 11):',
      explain: 'range stops before its end value, so range(1, 10) never reaches 10.',
    }),
  ],

  // Loops with lists
  'p-loop-2': [
    predict({
      kicker: K,
      title: 'Loop over a list',
      lang: 'python',
      lines: ['fares = [120, 80, 200]', 'total = 0', 'for f in fares:', '    total += f', 'print(total)'],
      answer: '400',
      explain: 'The loop visits each fare once: 120 + 80 + 200 = 400.',
    }),
    predict({
      kicker: K,
      title: 'append and len',
      lang: 'python',
      lines: ['stops = ["Delhi", "Agra"]', 'stops.append("Jaipur")', 'print(len(stops), stops[-1])'],
      answer: '3 Jaipur',
      explain: 'append adds to the end, so there are 3 stops and the last one ([-1]) is Jaipur.',
    }),
    order({
      kicker: K,
      title: 'Find the cheapest fare',
      instructions: 'Arrange the lines so the program prints the smallest fare.',
      lang: 'python',
      lines: ['fares = [450, 120, 300]', 'cheapest = fares[0]', 'for f in fares:', '    if f < cheapest:', '        cheapest = f', 'print(cheapest)'],
      output: ['120'],
      explain: 'Start with the first fare, then replace it whenever a smaller one comes along.',
    }),
    tap({
      kicker: K,
      title: 'Tap the loop variable',
      instructions: 'Which name takes each value from the list in turn?',
      lang: 'python',
      lines: ['names = ["Ravi", "Meena", "Arjun"]', 'for person in names:', '    print("Hi", person)'],
      target: { line: 1, token: 'person' },
      explain: 'In "for person in names", person holds one name per round of the loop.',
    }),
  ],

  // List comprehensions
  'p-comp-1': [
    predict({
      kicker: K,
      title: 'Squares',
      lang: 'python',
      lines: ['print([n * n for n in range(1, 5)])'],
      answer: '[1, 4, 9, 16]',
      explain: 'The comprehension squares each n from 1 to 4.',
    }),
    predict({
      kicker: K,
      title: 'With a condition',
      lang: 'python',
      lines: ['marks = [35, 82, 47, 91, 28]', 'print([m for m in marks if m >= 40])'],
      answer: '[82, 47, 91]',
      explain: 'Only marks that pass the if (40 or more) are kept, in their original order.',
    }),
    quiz({
      prompt: 'Which comprehension gives the lengths of the words?',
      lang: 'python',
      code: ['words = ["chai", "samosa", "dosa"]'],
      options: ['[len(w) for w in words]', '[w for len(w) in words]', '[len(words) for w in words]', 'len([w for w in words])'],
      right: 'Right: [4, 6, 4]. The expression before "for" is what goes into the new list.',
      wrong: 'Put what you want in the list first (len(w)), then "for w in words".',
      mono: true,
    }),
    bug({
      kicker: K,
      title: 'Find the bug',
      instructions: 'This should print only the even numbers: [2, 4, 6]. Tap the buggy line.',
      lang: 'python',
      lines: ['nums = [1, 2, 3, 4, 5, 6]', 'evens = [n for n in nums if n % 2 == 1]', 'print(evens)'],
      bug: 1,
      fix: 'evens = [n for n in nums if n % 2 == 0]',
      explain: 'Even numbers leave remainder 0 when divided by 2; remainder 1 means odd.',
    }),
  ],

  // def and return
  'p-fn-1': [
    predict({
      kicker: K,
      title: 'Call a function',
      lang: 'python',
      lines: ['def fare(km):', '    return 20 + km * 2', '', 'print(fare(10))'],
      answer: '40',
      explain: 'fare(10) works out 20 + 10 * 2 = 40 and returns it to print.',
    }),
    predict({
      kicker: K,
      title: 'print vs return',
      lang: 'python',
      lines: ['def greet(name):', '    print("Hello", name)', '', 'result = greet("Zoya")', 'print(result)'],
      answer: 'Hello Zoya\nNone',
      accept: ['Hello Zoya None'],
      explain: 'greet prints a greeting but returns nothing, and a function with no return gives None.',
    }),
    bug({
      kicker: K,
      title: 'Find the bug',
      instructions: 'average([4, 6, 8]) should give 6.0. Tap the buggy line.',
      lang: 'python',
      lines: ['def average(nums):', '    total = sum(nums)', '    print(total / len(nums))', '', 'result = average([4, 6, 8])', 'print(result)'],
      bug: 2,
      fix: '    return total / len(nums)',
      explain: 'The function must return the answer so the caller can use it. Printing it inside gives None back.',
    }),
    order({
      kicker: K,
      title: 'Build a function',
      instructions: 'Arrange the lines so the program prints the bigger of two numbers.',
      lang: 'python',
      lines: ['def bigger(a, b):', '    if a > b:', '        return a', '    return b', 'print(bigger(7, 12))'],
      output: ['12'],
      explain: 'If a isn’t bigger, the function skips the first return and reaches "return b".',
    }),
  ],

  // Dictionaries
  'p-dict-1': [
    predict({
      kicker: K,
      title: 'Look up a value',
      lang: 'python',
      lines: ['codes = {"NDLS": "New Delhi", "CSMT": "Mumbai"}', 'print(codes["CSMT"])'],
      answer: 'Mumbai',
      explain: 'A dictionary maps keys to values; codes["CSMT"] gives the value stored under that key.',
    }),
    predict({
      kicker: K,
      title: 'get with a default',
      lang: 'python',
      lines: ['stock = {"tea": 12, "coffee": 0}', 'print(stock.get("milk", 0), stock.get("tea", 0))'],
      answer: '0 12',
      explain: 'get returns the default (0) when the key is missing, instead of raising an error.',
    }),
    order({
      kicker: K,
      title: 'Count the votes',
      instructions: 'Arrange the lines so the program counts each vote and prints the totals.',
      lang: 'python',
      lines: ['votes = ["Ravi", "Meena", "Ravi"]', 'count = {}', 'for v in votes:', '    count[v] = count.get(v, 0) + 1', 'print(count)'],
      output: ["{'Ravi': 2, 'Meena': 1}"],
      explain: 'For each vote, take the current count (0 if new), add 1 and store it back.',
    }),
    bug({
      kicker: K,
      title: 'Find the bug',
      instructions: 'This should print each team with its runs. Tap the buggy line.',
      lang: 'python',
      lines: ['runs = {"India": 287, "Australia": 251}', 'for team, score in runs:', '    print(team, score)'],
      bug: 1,
      fix: 'for team, score in runs.items():',
      explain: 'Looping over a dictionary gives only its keys. .items() gives (key, value) pairs.',
    }),
  ],

  // Classes and objects
  'p-class-1': [
    predict({
      kicker: K,
      title: 'Make an object',
      lang: 'python',
      lines: [
        'class Train:',
        '    def __init__(self, name, seats):',
        '        self.name = name',
        '        self.seats = seats',
        '',
        't = Train("Rajdhani", 400)',
        'print(t.name, t.seats)',
      ],
      answer: 'Rajdhani 400',
      explain: '__init__ stores the values on the object, and t.name and t.seats read them back.',
    }),
    predict({
      kicker: K,
      title: 'A method changes the object',
      lang: 'python',
      lines: [
        'class Wallet:',
        '    def __init__(self):',
        '        self.coins = 0',
        '    def add(self, n):',
        '        self.coins += n',
        '',
        'w = Wallet()',
        'w.add(30)',
        'w.add(15)',
        'print(w.coins)',
      ],
      answer: '45',
      explain: 'Each call to add updates the same object’s coins: 0 + 30 + 15.',
    }),
    bug({
      kicker: K,
      title: 'Find the bug',
      instructions: 'Booking a seat should lower the seats left. Tap the buggy line.',
      lang: 'python',
      lines: [
        'class Bus:',
        '    def __init__(self):',
        '        self.left = 40',
        '    def book(self):',
        '        left = self.left - 1',
        '',
        'b = Bus()',
        'b.book()',
        'print(b.left)',
      ],
      bug: 4,
      fix: '        self.left = self.left - 1',
      explain: 'Without self., "left" is just a local variable that disappears when book ends.',
    }),
    quiz({
      prompt: 'In a method, what does self refer to?',
      options: ['The object the method was called on', 'The class itself', 'The first argument you pass in brackets', 'A copy of the object'],
      right: 'Right. In w.add(30), self is w.',
      wrong: 'Python passes the object automatically: in w.add(30), self is w and n is 30.',
    }),
  ],

  // Handling errors
  'p-err-1': [
    predict({
      kicker: K,
      title: 'Catch an error',
      lang: 'python',
      lines: ['try:', '    print(10 / 0)', 'except ZeroDivisionError:', '    print("Cannot divide by zero")'],
      answer: 'Cannot divide by zero',
      explain: 'Dividing by zero raises ZeroDivisionError, so the except block runs instead.',
    }),
    predict({
      kicker: K,
      title: 'Bad input',
      lang: 'python',
      lines: ['for text in ["12", "abc", "7"]:', '    try:', '        print(int(text) * 2)', '    except ValueError:', '        print("skip")'],
      answer: '24\nskip\n14',
      accept: ['24 skip 14'],
      explain: 'int("abc") raises ValueError, which is caught; the loop carries on with "7".',
    }),
    quiz({
      prompt: 'Which error does this raise?',
      lang: 'python',
      code: ['marks = {"maths": 90}', 'print(marks["science"])'],
      options: ['KeyError', 'IndexError', 'ValueError', 'NameError'],
      right: 'Right. Asking a dictionary for a key it doesn’t have raises KeyError.',
      wrong: 'The dictionary has no "science" key. A missing dictionary key raises KeyError.',
      mono: true,
    }),
    bug({
      kicker: K,
      title: 'Find the bug',
      instructions: 'This should print "Not a number" instead of crashing. Tap the buggy line.',
      lang: 'python',
      lines: ['try:', '    age = int("twelve")', 'except ZeroDivisionError:', '    print("Not a number")'],
      bug: 2,
      fix: 'except ValueError:',
      explain: 'int("twelve") raises ValueError, so that is the error to catch.',
    }),
  ],

  // Break a problem down
  'p-ps-1': [
    order({
      kicker: K,
      title: 'Count the vowels',
      instructions: 'Arrange the lines so the program counts the vowels in a word.',
      lang: 'python',
      lines: ['word = "education"', 'count = 0', 'for ch in word:', '    if ch in "aeiou":', '        count += 1', 'print(count)'],
      output: ['5'],
      explain: 'Go letter by letter and add 1 whenever the letter is a vowel. "education" has 5.',
    }),
    predict({
      kicker: K,
      title: 'Reverse it',
      lang: 'python',
      lines: ['word = "level"', 'print(word[::-1] == word)'],
      answer: 'True',
      explain: '[::-1] reverses the string. "level" reads the same backwards, so it is a palindrome.',
    }),
    predict({
      kicker: K,
      title: 'Step by step',
      lang: 'python',
      lines: ['n = 1234', 'total = 0', 'while n > 0:', '    total += n % 10', '    n //= 10', 'print(total)'],
      answer: '10',
      explain: 'n % 10 takes the last digit and n //= 10 removes it: 4 + 3 + 2 + 1 = 10.',
    }),
    bug({
      kicker: K,
      title: 'Find the bug',
      instructions: 'This should print the largest number. Tap the buggy line.',
      lang: 'python',
      lines: ['nums = [-5, -2, -9]', 'best = 0', 'for n in nums:', '    if n > best:', '        best = n', 'print(best)'],
      bug: 1,
      fix: 'best = nums[0]',
      explain: 'Starting at 0 is wrong when every number is negative. Start with the first number instead.',
    }),
  ],
};
